
CREATE VIEW VW_ALEATORIO AS SELECT RAND() AS VALUE

SELECT * FROM VW_ALEATORIO

CREATE FUNCTION NumeroAleatorio(@VALOR_INICIAL INT, @VALOR_FINAL INT) RETURNS INT
AS
BEGIN
	DECLARE @ALEATORIO INT
	DECLARE @ALEATORIO_FLOAT FLOAT
	SELECT @ALEATORIO_FLOAT = VALUE FROM VW_ALEATORIO
	SET @ALEATORIO = ROUND(((@VALOR_FINAL - @VALOR_INICIAL - 1) * @ALEATORIO_FLOAT + @VALOR_INICIAL), 0)
	RETURN @ALEATORIO
END

SELECT dbo.NumeroAleatorio(100,1000)


DECLARE @TABELA TABLE(NUMEROS_ALEATORIO INT)
DECLARE @CONTADOR INT
SET @CONTADOR = 1
WHILE @CONTADOR <= 100
BEGIN
	INSERT INTO @TABELA (NUMEROS_ALEATORIO)
	VALUES(dbo.NumeroAleatorio(0,1000))
	SET @CONTADOR += 1
END
SELECT * FROM @TABELA
