-- CLIENTE ALEATORIO

CREATE FUNCTION EntidadeAleatoria (@TIPO AS VARCHAR(20)) RETURNS VARCHAR(20)
AS
BEGIN
	DECLARE @ENTIDADE_ALEATORIA VARCHAR(20)
	DECLARE @TABELA TABLE (CODIGO VARCHAR(20))
	DECLARE @VALOR_INICIAL INT
	DECLARE @VALOR_FINAL INT 
	DECLARE @ALEATORIO INT
	DECLARE @CONTADOR INT

	IF @TIPO = 'CLIENTES'
	BEGIN
		INSERT INTO @TABELA (CODIGO) SELECT CPF FROM [TABELA DE CLIENTES]
	END
	BEGIN
	IF @TIPO = 'VENDEDORES'
		INSERT INTO @TABELA (CODIGO) SELECT MATRICULA FROM [TABELA DE VENDEDORES]
	END
	IF @TIPO = 'PRODUTOS'
	BEGIN
		INSERT INTO @TABELA (CODIGO) SELECT [CODIGO DO PRODUTO] FROM [TABELA DE PRODUTOS]
	END

	SET @CONTADOR = 1
	SET @VALOR_INICIAL = 1
	SELECT @VALOR_FINAL = COUNT(*) FROM @TABELA
	SET @ALEATORIO = dbo.NumeroAleatorio(@VALOR_INICIAL, @VALOR_FINAL)
	DECLARE CURSOR1 CURSOR FOR SELECT CODIGO FROM @TABELA
	OPEN CURSOR1
	FETCH NEXT FROM CURSOR1 INTO @ENTIDADE_ALEATORIA
	WHILE @CONTADOR < @ALEATORIO
	BEGIN
		FETCH NEXT FROM CURSOR1 INTO @ENTIDADE_ALEATORIA
		SET @CONTADOR = @CONTADOR + 1
	END
	CLOSE CURSOR1
	DEALLOCATE CURSOR1

	RETURN @ENTIDADE_ALEATORIA
END

SELECT [dbo].[EntidadeAleatoria]('CLIENTES'), [dbo].[EntidadeAleatoria]('VENDEDORES'), [dbo].[EntidadeAleatoria]('PRODUTOS')


DECLARE @CLIENTE VARCHAR(20)
DECLARE @VENDEDOR VARCHAR(20)
DECLARE @PRODUTO VARCHAR(20)

SET @CLIENTE = [dbo].[EntidadeAleatoria]('CLIENTES')
SET @VENDEDOR = [dbo].[EntidadeAleatoria]('VENDEDOR')
SET @PRODUTO = [dbo].[EntidadeAleatoria]('PRODUTO')

PRINT @CLIENTE
PRINT @VENDEDOR
PRINT @PRODUTO










