CREATE TABLE TAB_FATURAMENTO(
DATA_VENDA DATE NULL, 
TOTAL_VENDA FLOAT)

CREATE TRIGGER TG_ITENS_VENDIDOS
ON [ITENS NOTAS FISCAIS]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	DELETE FROM TAB_FATURAMENTO;
	
	INSERT INTO TAB_FATURAMENTO (DATA_VENDA, TOTAL_VENDA)
	SELECT A.DATA AS DATA_VENDA, SUM(B.QUANTIDADE * B.PREÇO) AS TOTAL_VENDA
	FROM [NOTAS FISCAIS] A INNER JOIN [ITENS NOTAS FISCAIS] B
	ON A.NUMERO = B.NUMERO
	GROUP BY A.DATA;
END;

SELECT * FROM [NOTAS FISCAIS]
SELECT * FROM [TABELA DE VENDEDORES]
SELECT * FROM [TABELA DE PRODUTOS]

INSERT [NOTAS FISCAIS] (NUMERO, DATA, CPF, MATRICULA, IMPOSTO)
VALUES ('999999', '2023-04-25', '1471156710', '00235', 0.18)

INSERT INTO [ITENS NOTAS FISCAIS] (NUMERO, [CODIGO DO PRODUTO], QUANTIDADE, PREÇO)
VALUES('999999', '1002334', 100,1)

INSERT INTO [ITENS NOTAS FISCAIS] (NUMERO, [CODIGO DO PRODUTO], QUANTIDADE, PREÇO)
VALUES('999999', '1002767', 100,1)

SELECT * FROM TAB_FATURAMENTO WHERE YEAR(DATA_VENDA) = 2023













