SELECT BAIRRO, ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES]
WHERE ESTADO = 'SP' GROUP BY BAIRRO, ESTADO

SELECT BAIRRO, ESTADO, SUM([LIMITE DE CREDITO]) AS SOMA_LIMITE FROM [TABELA DE CLIENTES]
WHERE ESTADO = 'SP' GROUP BY BAIRRO, ESTADO HAVING SUM([LIMITE DE CREDITO]) >= 140000

SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO
HAVING SUM([LIMITE DE CREDITO]) >= 850000

SELECT EMBALAGEM, SUM([PREÇO DE LISTA]) AS SOMA, MAX([PREÇO DE LISTA]) AS MAX_PREÇO,
MIN([PREÇO DE LISTA]) AS MIN_PREÇO
FROM [dbo].[TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]), MIN([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS]
GROUP BY EMBALAGEM HAVING SUM([PREÇO DE LISTA]) <= 80


SELECT EMBALAGEM, MAX([PREÇO DE LISTA]), MIN([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS]
GROUP BY EMBALAGEM HAVING SUM([PREÇO DE LISTA]) <= 80 AND MAX([PREÇO DE LISTA]) >= 6

/* Quais são os clientes que fizeram mais de 2000 compras em 2016? */

SELECT CPF, COUNT(*) FROM [NOTAS FISCAIS] WHERE YEAR(DATA) = 2016 GROUP BY CPF 
HAVING COUNT(*) > 2000