
CREATE TABLE CLIENTES(
CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(100) NULL,
ENDERECO VARCHAR(150) NULL,
BAIRRO VARCHAR(50) NULL,
CIDADE VARCHAR(50) NULL,
ESTADO VARCHAR(50) NULL,
CEP VARCHAR(8) NULL,
[DATA NASCIMENTO] DATE NULL,
IDADE INT NULL,
SEXO VARCHAR(1) NULL,
[LIMITE CREDITO] FLOAT NULL,
[VOLUME COMPRA] FLOAT NULL,
[PRIMEIRA COMPRA] BIT NULL,
CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED (CPF)
)