SELECT * FROM [TABELA DE CLIENTES]

SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT * FROM [NOTAS FISCAIS]

SELECT TC.NOME, NF.DATA, INF.QUANTIDADE FROM [TABELA DE CLIENTES] TC 
INNER JOIN [NOTAS FISCAIS] NF ON TC.CPF = NF.CPF
INNER JOIN [ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO


SELECT TC.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120),1, 7) AS DATA_CONVERTIDA, INF.QUANTIDADE FROM [TABELA DE CLIENTES] TC 
INNER JOIN [NOTAS FISCAIS] NF ON TC.CPF = NF.CPF
INNER JOIN [ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO


SELECT TC.NOME, CQ.DATA_CONVERTIDA, CQ.QUANTIDADE_MES, TC.[VOLUME DE COMPRA]
FROM
(SELECT TC.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120),1, 7) AS DATA_CONVERTIDA, 
SUM(INF.QUANTIDADE) AS QUANTIDADE_MES 
FROM [TABELA DE CLIENTES] TC 
INNER JOIN [NOTAS FISCAIS] NF ON TC.CPF = NF.CPF
INNER JOIN [ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO
GROUP BY TC.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120),1, 7)) CQ
INNER JOIN [TABELA DE CLIENTES] TC ON TC.CPF = CQ.CPF


SELECT AUX1.NOME, AUX1.ANO_MES, AUX1.QUANTIDADE_MES,
CASE WHEN AUX1.QUANTIDADE_MES <= AUX1.[VOLUME DE COMPRA] THEN 'VENDA VÁLIDA'
WHEN AUX1.QUANTIDADE_MES > AUX1.[VOLUME DE COMPRA] THEN 'VENDA INVÁLIDA'
END AS STATUS_VENDA
FROM
(SELECT TC.NOME, CQ.ANO_MES, CQ.QUANTIDADE_MES, TC.[VOLUME DE COMPRA]
FROM
(SELECT TC.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120),1, 7) AS ANO_MES, 
SUM(INF.QUANTIDADE) AS QUANTIDADE_MES 
FROM [TABELA DE CLIENTES] TC 
INNER JOIN [NOTAS FISCAIS] NF ON TC.CPF = NF.CPF
INNER JOIN [ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO
GROUP BY TC.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120),1, 7)) CQ
INNER JOIN [TABELA DE CLIENTES] TC ON TC.CPF = CQ.CPF) AUX1
ORDER BY AUX1.NOME, AUX1.ANO_MES



