SELECT A.[CPF], A.NOME, SUM(C.QUANTIDADE * C.PREÇO) AS FATURAMENTO
FROM [TABELA DE CLIENTES] A INNER JOIN [NOTAS FISCAIS] B
ON A.CPF = B.CPF AND YEAR(B.DATA) = 2016
INNER JOIN [ITENS NOTAS FISCAIS] C ON B.NUMERO = C.NUMERO
GROUP BY A.CPF, A.NOME

CREATE TYPE ListaClientes AS TABLE (CPF VARCHAR(12) NOT NULL)

DECLARE @Lista AS ListaClientes
INSERT INTO @Lista (CPF) VALUES ('492472718'), ('50534475787'), ('19290992743')

SELECT A.CPF, A.NOME, SUM(C.QUANTIDADE * C.PREÇO) AS FATURAMENTO
FROM [TABELA DE CLIENTES] A INNER JOIN [NOTAS FISCAIS] B
ON A.CPF = B.CPF AND YEAR(B.DATA) = 2016
INNER JOIN [ITENS NOTAS FISCAIS] C ON B.NUMERO = C.NUMERO
INNER JOIN @Lista D ON A.CPF = D.CPF
GROUP BY A.CPF, A.NOME

CREATE PROCEDURE FaturamentoClientes2016
@LISTA AS ListaClientes READONLY
AS
SELECT A.CPF, A.NOME, SUM(C.QUANTIDADE * C.PREÇO) AS FATURAMENTO
FROM [TABELA DE CLIENTES] A INNER JOIN [NOTAS FISCAIS] B
ON A.CPF = B.CPF AND YEAR(B.DATA) = 2016
INNER JOIN [ITENS NOTAS FISCAIS] C ON B.NUMERO = C.NUMERO
INNER JOIN @LISTA D ON A.CPF = D.CPF
GROUP BY A.CPF, A.NOME

DECLARE @Lista AS ListaClientes
INSERT INTO @Lista (CPF) VALUES ('492472718'), ('50534475787'), ('19290992743')

EXEC FaturamentoClientes2016 @LISTA = @Lista




CREATE TYPE ListaDatas AS TABLE (DATANOTA DATE NOT NULL)

CREATE PROCEDURE ListaNumeroNotas 
@ListaDatas AS ListaDatas READONLY
AS SELECT DATA, COUNT(*) AS NUMERO FROM [NOTAS FISCAIS]
WHERE DATA IN (SELECT DATANOTA FROM @ListaDatas)
GROUP BY DATA

DECLARE @ListaDatas AS ListaDatas
INSERT INTO @ListaDatas (DATANOTA) VALUES ('20180101'), ('20180102'), ('20180103')

EXEC ListaNumeroNotas @ListaDatas = @ListaDatas