
CREATE PROCEDURE CalculaIdade
AS
BEGIN
	 UPDATE [TABELA DE CLIENTES] SET IDADE = DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE())
END

INSERT INTO [TABELA DE CLIENTES](CPF, NOME, [ENDERECO 1], BAIRRO, CIDADE, ESTADO, CEP, [DATA DE NASCIMENTO], 
SEXO, [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA])
VALUES ('09877656787', 'BRUNO HOFFMANN', 'BOA SAUDE', 'GUAJUVIRAS', 'CANOAS',
'RS', '90000000','19960728', 'M', 120000, 12000, 120000 )

EXEC CalculaIdade

SELECT * FROM [TABELA DE CLIENTES] WHERE CPF = '09877656787'

SELECT * FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF ON
	NF.NUMERO = INF.NUMERO

/* Comece determinando a consulta que seleciona todas as notas fiscais dentro do mês/ano para um 
tipo de produto; */

select * from [NOTAS FISCAIS]
select * from [ITENS NOTAS FISCAIS]
select * from [TABELA DE PRODUTOS]

SELECT * FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF ON
NF.NUMERO = INF.NUMERO
INNER JOIN [TABELA DE PRODUTOS] TP ON
INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE MONTH(NF.DATA) = 1 AND YEAR(NF.DATA) = 2017
AND TP.EMBALAGEM = 'PET'

/* Comando UPDATE para alterar o valor do campo IMPOSTO: */

UPDATE NF SET NF.IMPOSTO = 0.18
FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
WHERE MONTH(NF.DATA) = 1 AND YEAR(NF.DATA) = 2017
AND TP.EMBALAGEM = 'Lata'

/* Construção da stored procedure: */

CREATE PROCEDURE AtualizaImposto @MES AS INT, @ANO AS INT, @EMBALAGEM AS VARCHAR(10), @IMPOSTO AS FLOAT
AS
BEGIN
	UPDATE NF SET NF.IMPOSTO = @IMPOSTO FROM [NOTAS FISCAIS] NF
	INNER JOIN [ITENS NOTAS FISCAIS] INF
		ON NF.NUMERO = INF.NUMERO
	INNER JOIN [TABELA DE PRODUTOS] TP 
		ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
	WHERE MONTH(NF.DATA) = @MES AND YEAR(NF.DATA) = @ANO
	AND TP.EMBALAGEM = @EMBALAGEM
END

EXEC AtualizaImposto @MES = 2, @ANO = 2017, @EMBALAGEM = 'PET', @IMPOSTO = 0.16

SELECT * FROM [ITENS NOTAS FISCAIS]