DECLARE @LIMITE_MINIMO INT, @LIMITE_MAXIMO INT, @LIMITE_BREAK INT

SET @LIMITE_MINIMO = 1
SET @LIMITE_MAXIMO = 10
SET @LIMITE_BREAK = 12

WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
	PRINT @LIMITE_MINIMO
	SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1
	IF @LIMITE_MINIMO = @LIMITE_BREAK
	BEGIN
		PRINT 'Saindo por causa do BREAK'
		BREAK
	END
END


/* Faça um script que, a partir do dia 01/01/2017, conte o número de notas fiscais até o dia 10/01/2017. 
Imprima a data e o número de notas fiscais. */

IF OBJECT_ID ('TABELA DE DIAS E NOTAS FISCAIS', 'U') IS NOT NULL
	DROP TABLE [TABELA DE DIAS E NOTAS FISCAIS]
CREATE TABLE [TABELA DE DIAS E NOTAS FISCAIS]([DATA] DATE, [NUMNOTAS] INT)

DECLARE @DATAINICIAL DATE
DECLARE @DATAFINAL DATE
DECLARE @NUMNOTAS INT
SET @DATAINICIAL = '20170101'
SET @DATAFINAL = '20170110'
WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
	SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE DATA = @DATAINICIAL
	INSERT INTO [TABELA DE DIAS E NOTAS FISCAIS]([DATA], [NUMNOTAS]) VALUES (@DATAINICIAL, @NUMNOTAS)
	SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
END

SELECT * FROM [TABELA DE DIAS E NOTAS FISCAIS]


