SELECT * FROM [TABELA DE PRODUTOS]

SELECT * FROM [NOTAS FISCAIS]

SELECT * FROM [ITENS NOTAS FISCAIS]



SELECT AUX1.SABOR, AUX1.ANO, CONVERT(DECIMAL(15,2), AUX1.FATURAMENTO) AS FATURAMENTO, 
CONVERT(VARCHAR, CONVERT(DECIMAL(15,2), (AUX1.FATURAMENTO / AUX2.TOTAL) * 100)) + ' %' AS PERCENTUAL
FROM
(SELECT TP.SABOR, YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM [TABELA DE PRODUTOS] TP INNER JOIN [ITENS NOTAS FISCAIS] INF
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO] INNER JOIN
[NOTAS FISCAIS] NF ON INF.NUMERO = NF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY TP.SABOR, YEAR(NF.DATA)) AUX1
INNER JOIN
(SELECT YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS TOTAL
FROM [TABELA DE PRODUTOS] TP INNER JOIN [ITENS NOTAS FISCAIS] INF
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO] INNER JOIN
[NOTAS FISCAIS] NF ON INF.NUMERO = NF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY YEAR(NF.DATA)) AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC




/* Modifique o relatório, mas agora para ver o ranking das vendas por tamanho. */


SELECT AUX1.TAMANHO, AUX1.ANO, CONVERT(DECIMAL(15,2), AUX1.FATURAMENTO) AS FATURAMENTO, 
CONVERT(VARCHAR, CONVERT(DECIMAL(15,2), (AUX1.FATURAMENTO / AUX2.TOTAL) * 100)) + ' %' AS PERCENTUAL
FROM
(SELECT TP.TAMANHO, YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM [TABELA DE PRODUTOS] TP INNER JOIN [ITENS NOTAS FISCAIS] INF
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO] INNER JOIN
[NOTAS FISCAIS] NF ON INF.NUMERO = NF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY TP.TAMANHO, YEAR(NF.DATA)) AUX1
INNER JOIN
(SELECT YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS TOTAL
FROM [TABELA DE PRODUTOS] TP INNER JOIN [ITENS NOTAS FISCAIS] INF
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO] INNER JOIN
[NOTAS FISCAIS] NF ON INF.NUMERO = NF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY YEAR(NF.DATA)) AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC



