SELECT * FROM [TABELA DE CLIENTES]

CREATE FUNCTION ListaNotasCliente (@CPF AS VARCHAR(12)) RETURNS TABLE
AS
RETURN SELECT * FROM [NOTAS FISCAIS] WHERE CPF = @CPF

SELECT * FROM [dbo].[ListaNotasCliente]('1471156710')

SELECT A.CPF, A.NUM_NOTA, B.TOTAL_FATURAMENTO
FROM
(SELECT CPF, (SELECT COUNT(*) FROM [dbo].[ListaNotasCliente](CPF)) AS NUM_NOTA
FROM [TABELA DE CLIENTES]) A
INNER JOIN
(SELECT CPF, SUM([dbo].[FaturamentoNota](NUMERO)) AS TOTAL_FATURAMENTO
FROM [NOTAS FISCAIS] GROUP BY CPF) B
ON A.CPF = B.CPF

/* Transforme isto em uma função chamada FuncTabelaNotas, onde o resultado é a consulta acima. 
Lembrando que a data inicial e final serão parâmetros desta função. Depois, teste a função através de 
um SELECT. */

SELECT DISTINCT DATA, [dbo].[NUMERONOTAS](DATA) AS NUMERO 
FROM [NOTAS FISCAIS] WHERE DATA >= '20170101' AND DATA <= '20170110'

CREATE FUNCTION FuncTabelaNotas(@DATA_INICIAL DATE, @DATA_FINAL DATE) RETURNS TABLE
AS
RETURN SELECT DISTINCT DATA, [dbo].[NumeroNotas](DATA) AS NUMERO 
FROM [NOTAS FISCAIS] WHERE DATA >= @DATA_INICIAL AND DATA <= @DATA_FINAL

SELECT * FROM [dbo].[FuncTabelaNotas]('20170101', '20170110')