select * from [TABELA DE PRODUTOS];

UPDATE [TABELA DE PRODUTOS]
SET[PRECO DE LISTA] = 3
WHERE [CODIGO DO PRODUTO] = '544931'

UPDATE [TABELA DE PRODUTOS]
SET[PRECO DE LISTA] = 7.50, [EMBALAGEM] = 'Garrafa'
WHERE [CODIGO DO PRODUTO] = '1088126'

