ALTER TABLE [TABELA DE PRODUTOS] ALTER COLUMN [CODIGO DO PRODUTO] VARCHAR(20) NOT NULL;

ALTER TABLE[TABELA DE PRODUTOS] ADD CONSTRAINT PK_TABELA_DE_PRODUTOS
PRIMARY KEY CLUSTERED ([CODIGO DO PRODUTO]);

DELETE FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1078680'

INSERT INTO [TABELA DE PRODUTOS]
VALUES
('1078680', 
'Frescor do verão - 470ml - Manga',
'Garrafa',
'470ml',
'Manga', 
7)